/**
 * Customers Registration APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '@apimatic/core';
import { ApiResponse, RequestOptions } from '../core';
import { unknown } from '../schema';
import { BaseController } from './baseController';

export class HealthCheckController extends BaseController {
  /**
   * Health Check
   *
   * @return Response from the API call
   */
  async healthCheck(
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<unknown>> {
    const req = this.createRequest('GET', '/health-check');
    req.throwOn(400, ApiError, 'Bad Request');
    return req.callAsJson(unknown(), requestOptions);
  }
}
